apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-app-backend
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "sa-app-backend@practice-502506.iam.gserviceaccount.com"